### PR TITLE
Fix broken link

### PR DESCRIPTION
**Pull request by almet**
Quelques autres retours (pour l'instant):

1. Au départ, tu montre comment faire un svg avec les élements de base, mais tu ne précise pas vraiment comment fonctionne la syntaxe utilisée. Pour mon cas, je sais maintenant comment ça fonctionne, mais je sais aussi que c'est un truc qui m'a posé problème par le passé.
2. Trop bien les diffs ! Un truc possible en restructured text mais pas en markdown (à ma connaissance) !
3. Pas sur que ce soit utile d'avoir les commits liés sous les diffs. Peut-être qu'indiquer au début de l'article qu'il est possible de voir le tout sur un dépot (avec le pas à pas) ?

### CODE REVIEW

**Review by magopian — APPROVED** [review]
Oh wow thanks for those typos!

**Comment by magopian** [comment]
I'll answer in english just in case it's useful for somebody out there, and I know english isn't a problem for you ;)

1. interesting: I've tried to find a balance between "too much information" and "not enough", I might want to add some more info there following your feedback
2. I'm not sure I understand what you mean by "diffs work in restructured text but not in markdown": I've written the blog post in markdown, and used the `diff` syntax highlighting. Are you saying there's a better way to do that in restructured text?
3. do you think that those commit links below the diffs are adding to much cruft or noise? I thought it was convenient to have a "full view" of the diff, for example when I presented the diff splitted and interspersed with comments

**Comment by almet** [comment]
1. That's just a feedback, feel free to do whatever you think is best :-)
2. I though you were using rst when I wrote the feedback. But apparently I was wrong. (edit : apparently I was mistaken with the emphasize feature in rst. Screw me).
3. again, I personally don't feel they are needed in my case (I actually do not want to click to go elsewhere when reading an article, unless absolutely necessary). I'm not saying they should go away (who would I be, to tell you what you should do?!), but that in my case they weren't useful.

Thanks for the article, it's useful!

**Comment by magopian** [comment]
Thanks a lot for the feedback, will think about it <3

**Pull request merged**
